#!/usr/local/bin/python

from __future__ import print_function
from google_drive_concourse_resource_common import getServiceInstance
from google_drive_concourse_resource_common import putFile
from apiclient import errors
import json,sys



"""Takes a JSON request from stdin and puts a local file onto a google drive folder
  Args:
    fID: Folder ID to use for the uploaded file
    pFile: Path to the local file to upload including extension
  Returns:
    File ID of the uploaded file or exits(1) with a message indicating no file uploaded
"""
fID=''
pFile=''
cEmail=''
pID=''
cID=''
pKey=''

def main():
  req=json.load(sys.stdin)
  if req:
    fID=(req['source']['drive_folder_id'])
    pFile=(req['params']['file_name'])
    cEmail=(req['source']['drive_client_email'])
    pID=(req['source']['drive_private_key_id'])
    cID=(req['source']['drive_client_id'])
    pKey=(req['source']['drive_private_key'])
  else:
    print('No suitable request received', file=sys.stderr)
    sys.exit(1)
  drive_service = getServiceInstance(cEmail,pID,cID,pKey)
  response=putFile(drive_service,fID, pFile)
  if isinstance(response,errors.HttpError):
    print('File Not Uploaded', file=sys.stderr)
    sys.exit(1)
  else:
    metadata = []
    print('File ID {0} was uploaded successfully!' .format(response.get('id')),file=sys.stderr)
    print(json.dumps({"version": {"id": response.get('id'),
                                 "file_name": response.get('title')},
                      "metadata": metadata
                      }))
if __name__ == '__main__':
  main()
